const pageSettings = {
  "title": "OEM Parts Finder",
  "title_background_image": "//cdn.shopify.com/s...",
  "title_font_size": 36,
  "title_font_color": "#ff7801",
  "title_text_align": "start",
  "brand_order": "'Polaris',Arctic Cat,Honda,Can-Am,Ski-Doo,Sea-Doo,CF-Moto,Bombardier,GEM",
  "hover_color":"rgba(255,120,1,.8)",
  "header": "",
  "footer": "<p>some footer text</p>",
  "brand_logo_url_arctic-cat": "/img/logos/arctic-cat-oem-logo.webp",
  "brand_logo_url_bg_arctic-cat": "",
  "brand_logo_url_header_arctic-cat": "/img/logos/header-logos/arcticcat_white.webp",
  "title_color_arctic-cat": "#FFFFFF",
  "title_bg_arctic-cat": "#66BC29",
  "brand_logo_url_bombardier": "/img/logos/brp-oem-logo.webp",
  "brand_logo_url_bg_bombardier": "",
  "brand_logo_url_header_bombardier": "/img/logos/header-logos/brp_white.webp",
  "brand_logo_url_cf-moto": "/img/logos/cfmoto-oem-logo.webp",
  "brand_logo_url_bg_cf-moto": "",
  "brand_logo_url_header_cf-moto": "/img/logos/header-logos/cfmoto_white.webp",
  "brand_logo_url_can-am": "/img/logos/can-am-oem-logo.webp",
  "brand_logo_url_bg_can-am": "",
  "brand_logo_url_header_can-am": "/img/logos/header-logos/canam_white.webp",
  "brand_logo_url_gem": "/img/logos/gem-oem-logo.webp",
  "brand_logo_url_bg_gem": "",
  "brand_logo_url_header_gem": "/img/logos/header-logos/gem_white.webp",
  "brand_logo_url_honda": "/img/logos/honda-oem-logo.webp",
  "brand_logo_url_bg_honda": "",
  "brand_logo_url_header_honda": "/img/logos/header-logos/honda_white.webp",
  "brand_logo_url_polaris": "/img/logos/polaris-oem-logo.webp",
  "brand_logo_url_bg_polaris": "",
  "brand_logo_url_header_polaris": "/img/logos/header-logos/polaris_white.webp",
  "brand_logo_url_sea-doo": "/img/logos/sea-doo-oem-logo.webp",
  "brand_logo_url_bg_sea-doo": "",
  "brand_logo_url_header_sea-doo": "/img/logos/header-logos/sea-doo_white.webp",
  "brand_logo_url_ski-doo": "/img/logos/ski-doo-oem-logo.webp",
  "brand_logo_url_bg_ski-doo": "",
  "brand_logo_url_header_ski-doo": "/img/logos/header-logos/skidoo_white.webp",
  "title_color_bombardier": "#FFFFFF",
  "title_color_cf-moto": "#FFFFFF",
  "title_color_can-am": "#FFFFFF",
  "title_color_gem": "#FFFFFF",
  "title_color_honda": "#FFFFFF",
  "title_color_polaris": "#fda9a9",
  "title_color_sea-doo": "#fdce7f",
  "title_color_ski-doo": "#FFFFFF",
  "title_bg_bombardier": "#ff9100",
  "title_bg_cf-moto": "#C3161C",
  "title_bg_can-am": "#FFCB00",
  "title_bg_gem": "#1119a9",
  "title_bg_honda": "#FF0000",
  "title_bg_polaris": "#0167ff",
  "title_bg_sea-doo": "#007864",
  "title_bg_ski-doo": "#01d9ff",
}
